# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lamppost.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'lamppost.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elamppost.proto\x12\x08lamppost\"\xc6\x02\n\x0fLamppostCommand\x12\x32\n\x07turn_on\x18\x01 \x01(\x0b\x32\x1f.lamppost.LamppostTurnOnRequestH\x00\x12\x34\n\x08turn_off\x18\x02 \x01(\x0b\x32 .lamppost.LamppostTurnOffRequestH\x00\x12\x36\n\tget_state\x18\x03 \x01(\x0b\x32!.lamppost.LamppostGetStateRequestH\x00\x12\x44\n\x10simulate_failure\x18\x04 \x01(\x0b\x32(.lamppost.LamppostSimulateFailureRequestH\x00\x12@\n\x0eset_luminosity\x18\x05 \x01(\x0b\x32&.lamppost.LamppostSetLuminosityRequestH\x00\x42\t\n\x07\x63ommand\"\x17\n\x15LamppostTurnOnRequest\"\x18\n\x16LamppostTurnOffRequest\"\x19\n\x17LamppostGetStateRequest\" \n\x1eLamppostSimulateFailureRequest\":\n\x1cLamppostSetLuminosityRequest\x12\x1a\n\x12luminosity_percent\x18\x01 \x01(\x01\"\x90\x01\n\x10LamppostResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x03 \x01(\x08\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x1a\n\x12luminosity_percent\x18\x05 \x01(\x01\x12\x1e\n\x16\x65nergy_consumption_kwh\x18\x06 \x01(\x01\"M\n\x0fLamppostReading\x12\x1a\n\x12luminosity_percent\x18\x01 \x01(\x01\x12\x1e\n\x16\x65nergy_consumption_kwh\x18\x02 \x01(\x01\x42>Z<github.com/cbysousa/distributed-systems/internal/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lamppost_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/cbysousa/distributed-systems/internal/proto;proto'
  _globals['_LAMPPOSTCOMMAND']._serialized_start=29
  _globals['_LAMPPOSTCOMMAND']._serialized_end=355
  _globals['_LAMPPOSTTURNONREQUEST']._serialized_start=357
  _globals['_LAMPPOSTTURNONREQUEST']._serialized_end=380
  _globals['_LAMPPOSTTURNOFFREQUEST']._serialized_start=382
  _globals['_LAMPPOSTTURNOFFREQUEST']._serialized_end=406
  _globals['_LAMPPOSTGETSTATEREQUEST']._serialized_start=408
  _globals['_LAMPPOSTGETSTATEREQUEST']._serialized_end=433
  _globals['_LAMPPOSTSIMULATEFAILUREREQUEST']._serialized_start=435
  _globals['_LAMPPOSTSIMULATEFAILUREREQUEST']._serialized_end=467
  _globals['_LAMPPOSTSETLUMINOSITYREQUEST']._serialized_start=469
  _globals['_LAMPPOSTSETLUMINOSITYREQUEST']._serialized_end=527
  _globals['_LAMPPOSTRESPONSE']._serialized_start=530
  _globals['_LAMPPOSTRESPONSE']._serialized_end=674
  _globals['_LAMPPOSTREADING']._serialized_start=676
  _globals['_LAMPPOSTREADING']._serialized_end=753
# @@protoc_insertion_point(module_scope)
