services:
  gateway:
    build:
      context: ./gateway
    container_name: gateway
    network_mode: host

  weather-sensor:
    build:
      context: ./weather-sensor
    container_name: weather-sensor
    network_mode: host

  air-quality-sensor:
    build:
      context: ./air-quality-sensor
    container_name: air-quality-sensor
    network_mode: host


  lamppost:
    build:
      context: ./lamppost
    container_name: lamppost
    network_mode: host

