// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: air_quality.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AirQualityReading struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Co2Ppm                float64                `protobuf:"fixed64,1,opt,name=co2_ppm,json=co2Ppm,proto3" json:"co2_ppm,omitempty"`
	ParticulateMatterUgM3 float64                `protobuf:"fixed64,2,opt,name=particulate_matter_ug_m3,json=particulateMatterUgM3,proto3" json:"particulate_matter_ug_m3,omitempty"`
	AirQualityIndex       float64                `protobuf:"fixed64,3,opt,name=air_quality_index,json=airQualityIndex,proto3" json:"air_quality_index,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AirQualityReading) Reset() {
	*x = AirQualityReading{}
	mi := &file_air_quality_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AirQualityReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirQualityReading) ProtoMessage() {}

func (x *AirQualityReading) ProtoReflect() protoreflect.Message {
	mi := &file_air_quality_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirQualityReading.ProtoReflect.Descriptor instead.
func (*AirQualityReading) Descriptor() ([]byte, []int) {
	return file_air_quality_proto_rawDescGZIP(), []int{0}
}

func (x *AirQualityReading) GetCo2Ppm() float64 {
	if x != nil {
		return x.Co2Ppm
	}
	return 0
}

func (x *AirQualityReading) GetParticulateMatterUgM3() float64 {
	if x != nil {
		return x.ParticulateMatterUgM3
	}
	return 0
}

func (x *AirQualityReading) GetAirQualityIndex() float64 {
	if x != nil {
		return x.AirQualityIndex
	}
	return 0
}

var File_air_quality_proto protoreflect.FileDescriptor

const file_air_quality_proto_rawDesc = "" +
	"\n" +
	"\x11air_quality.proto\x12\n" +
	"airquality\"\x91\x01\n" +
	"\x11AirQualityReading\x12\x17\n" +
	"\aco2_ppm\x18\x01 \x01(\x01R\x06co2Ppm\x127\n" +
	"\x18particulate_matter_ug_m3\x18\x02 \x01(\x01R\x15particulateMatterUgM3\x12*\n" +
	"\x11air_quality_index\x18\x03 \x01(\x01R\x0fairQualityIndexB>Z<github.com/cbysousa/distributed-systems/internal/proto;protob\x06proto3"

var (
	file_air_quality_proto_rawDescOnce sync.Once
	file_air_quality_proto_rawDescData []byte
)

func file_air_quality_proto_rawDescGZIP() []byte {
	file_air_quality_proto_rawDescOnce.Do(func() {
		file_air_quality_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_air_quality_proto_rawDesc), len(file_air_quality_proto_rawDesc)))
	})
	return file_air_quality_proto_rawDescData
}

var file_air_quality_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_air_quality_proto_goTypes = []any{
	(*AirQualityReading)(nil), // 0: airquality.AirQualityReading
}
var file_air_quality_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_air_quality_proto_init() }
func file_air_quality_proto_init() {
	if File_air_quality_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_air_quality_proto_rawDesc), len(file_air_quality_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_air_quality_proto_goTypes,
		DependencyIndexes: file_air_quality_proto_depIdxs,
		MessageInfos:      file_air_quality_proto_msgTypes,
	}.Build()
	File_air_quality_proto = out.File
	file_air_quality_proto_goTypes = nil
	file_air_quality_proto_depIdxs = nil
}
