// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: cam.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CamCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*CamCommand_TurnOn
	//	*CamCommand_TurnOff
	//	*CamCommand_GetState
	//	*CamCommand_SimulateFailure
	Command       isCamCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CamCommand) Reset() {
	*x = CamCommand{}
	mi := &file_cam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CamCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CamCommand) ProtoMessage() {}

func (x *CamCommand) ProtoReflect() protoreflect.Message {
	mi := &file_cam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CamCommand.ProtoReflect.Descriptor instead.
func (*CamCommand) Descriptor() ([]byte, []int) {
	return file_cam_proto_rawDescGZIP(), []int{0}
}

func (x *CamCommand) GetCommand() isCamCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CamCommand) GetTurnOn() *CamTurnOnRequest {
	if x != nil {
		if x, ok := x.Command.(*CamCommand_TurnOn); ok {
			return x.TurnOn
		}
	}
	return nil
}

func (x *CamCommand) GetTurnOff() *CamTurnOffRequest {
	if x != nil {
		if x, ok := x.Command.(*CamCommand_TurnOff); ok {
			return x.TurnOff
		}
	}
	return nil
}

func (x *CamCommand) GetGetState() *CamGetStateRequest {
	if x != nil {
		if x, ok := x.Command.(*CamCommand_GetState); ok {
			return x.GetState
		}
	}
	return nil
}

func (x *CamCommand) GetSimulateFailure() *CamSimulateFailureRequest {
	if x != nil {
		if x, ok := x.Command.(*CamCommand_SimulateFailure); ok {
			return x.SimulateFailure
		}
	}
	return nil
}

type isCamCommand_Command interface {
	isCamCommand_Command()
}

type CamCommand_TurnOn struct {
	TurnOn *CamTurnOnRequest `protobuf:"bytes,1,opt,name=turn_on,json=turnOn,proto3,oneof"`
}

type CamCommand_TurnOff struct {
	TurnOff *CamTurnOffRequest `protobuf:"bytes,2,opt,name=turn_off,json=turnOff,proto3,oneof"`
}

type CamCommand_GetState struct {
	GetState *CamGetStateRequest `protobuf:"bytes,3,opt,name=get_state,json=getState,proto3,oneof"`
}

type CamCommand_SimulateFailure struct {
	SimulateFailure *CamSimulateFailureRequest `protobuf:"bytes,4,opt,name=simulate_failure,json=simulateFailure,proto3,oneof"`
}

func (*CamCommand_TurnOn) isCamCommand_Command() {}

func (*CamCommand_TurnOff) isCamCommand_Command() {}

func (*CamCommand_GetState) isCamCommand_Command() {}

func (*CamCommand_SimulateFailure) isCamCommand_Command() {}

type CamTurnOnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CamTurnOnRequest) Reset() {
	*x = CamTurnOnRequest{}
	mi := &file_cam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CamTurnOnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CamTurnOnRequest) ProtoMessage() {}

func (x *CamTurnOnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CamTurnOnRequest.ProtoReflect.Descriptor instead.
func (*CamTurnOnRequest) Descriptor() ([]byte, []int) {
	return file_cam_proto_rawDescGZIP(), []int{1}
}

type CamTurnOffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CamTurnOffRequest) Reset() {
	*x = CamTurnOffRequest{}
	mi := &file_cam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CamTurnOffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CamTurnOffRequest) ProtoMessage() {}

func (x *CamTurnOffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CamTurnOffRequest.ProtoReflect.Descriptor instead.
func (*CamTurnOffRequest) Descriptor() ([]byte, []int) {
	return file_cam_proto_rawDescGZIP(), []int{2}
}

type CamGetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CamGetStateRequest) Reset() {
	*x = CamGetStateRequest{}
	mi := &file_cam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CamGetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CamGetStateRequest) ProtoMessage() {}

func (x *CamGetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CamGetStateRequest.ProtoReflect.Descriptor instead.
func (*CamGetStateRequest) Descriptor() ([]byte, []int) {
	return file_cam_proto_rawDescGZIP(), []int{3}
}

type CamSimulateFailureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CamSimulateFailureRequest) Reset() {
	*x = CamSimulateFailureRequest{}
	mi := &file_cam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CamSimulateFailureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CamSimulateFailureRequest) ProtoMessage() {}

func (x *CamSimulateFailureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CamSimulateFailureRequest.ProtoReflect.Descriptor instead.
func (*CamSimulateFailureRequest) Descriptor() ([]byte, []int) {
	return file_cam_proto_rawDescGZIP(), []int{4}
}

type CamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CamResponse) Reset() {
	*x = CamResponse{}
	mi := &file_cam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CamResponse) ProtoMessage() {}

func (x *CamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CamResponse.ProtoReflect.Descriptor instead.
func (*CamResponse) Descriptor() ([]byte, []int) {
	return file_cam_proto_rawDescGZIP(), []int{5}
}

func (x *CamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CamResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *CamResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_cam_proto protoreflect.FileDescriptor

const file_cam_proto_rawDesc = "" +
	"\n" +
	"\tcam.proto\x12\x03cam\"\x83\x02\n" +
	"\n" +
	"CamCommand\x120\n" +
	"\aturn_on\x18\x01 \x01(\v2\x15.cam.CamTurnOnRequestH\x00R\x06turnOn\x123\n" +
	"\bturn_off\x18\x02 \x01(\v2\x16.cam.CamTurnOffRequestH\x00R\aturnOff\x126\n" +
	"\tget_state\x18\x03 \x01(\v2\x17.cam.CamGetStateRequestH\x00R\bgetState\x12K\n" +
	"\x10simulate_failure\x18\x04 \x01(\v2\x1e.cam.CamSimulateFailureRequestH\x00R\x0fsimulateFailureB\t\n" +
	"\acommand\"\x12\n" +
	"\x10CamTurnOnRequest\"\x13\n" +
	"\x11CamTurnOffRequest\"\x14\n" +
	"\x12CamGetStateRequest\"\x1b\n" +
	"\x19CamSimulateFailureRequest\"q\n" +
	"\vCamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06statusB>Z<github.com/cbysousa/distributed-systems/internal/proto;protob\x06proto3"

var (
	file_cam_proto_rawDescOnce sync.Once
	file_cam_proto_rawDescData []byte
)

func file_cam_proto_rawDescGZIP() []byte {
	file_cam_proto_rawDescOnce.Do(func() {
		file_cam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cam_proto_rawDesc), len(file_cam_proto_rawDesc)))
	})
	return file_cam_proto_rawDescData
}

var file_cam_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cam_proto_goTypes = []any{
	(*CamCommand)(nil),                // 0: cam.CamCommand
	(*CamTurnOnRequest)(nil),          // 1: cam.CamTurnOnRequest
	(*CamTurnOffRequest)(nil),         // 2: cam.CamTurnOffRequest
	(*CamGetStateRequest)(nil),        // 3: cam.CamGetStateRequest
	(*CamSimulateFailureRequest)(nil), // 4: cam.CamSimulateFailureRequest
	(*CamResponse)(nil),               // 5: cam.CamResponse
}
var file_cam_proto_depIdxs = []int32{
	1, // 0: cam.CamCommand.turn_on:type_name -> cam.CamTurnOnRequest
	2, // 1: cam.CamCommand.turn_off:type_name -> cam.CamTurnOffRequest
	3, // 2: cam.CamCommand.get_state:type_name -> cam.CamGetStateRequest
	4, // 3: cam.CamCommand.simulate_failure:type_name -> cam.CamSimulateFailureRequest
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_cam_proto_init() }
func file_cam_proto_init() {
	if File_cam_proto != nil {
		return
	}
	file_cam_proto_msgTypes[0].OneofWrappers = []any{
		(*CamCommand_TurnOn)(nil),
		(*CamCommand_TurnOff)(nil),
		(*CamCommand_GetState)(nil),
		(*CamCommand_SimulateFailure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cam_proto_rawDesc), len(file_cam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cam_proto_goTypes,
		DependencyIndexes: file_cam_proto_depIdxs,
		MessageInfos:      file_cam_proto_msgTypes,
	}.Build()
	File_cam_proto = out.File
	file_cam_proto_goTypes = nil
	file_cam_proto_depIdxs = nil
}
