// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: client.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ClientRequest_ListSources
	//	*ClientRequest_ListReadings
	//	*ClientRequest_SendCommand
	Request       isClientRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

func (x *ClientRequest) GetRequest() isClientRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ClientRequest) GetListSources() *ListSourcesRequest {
	if x != nil {
		if x, ok := x.Request.(*ClientRequest_ListSources); ok {
			return x.ListSources
		}
	}
	return nil
}

func (x *ClientRequest) GetListReadings() *ListReadingsRequest {
	if x != nil {
		if x, ok := x.Request.(*ClientRequest_ListReadings); ok {
			return x.ListReadings
		}
	}
	return nil
}

func (x *ClientRequest) GetSendCommand() *SendCommandRequest {
	if x != nil {
		if x, ok := x.Request.(*ClientRequest_SendCommand); ok {
			return x.SendCommand
		}
	}
	return nil
}

type isClientRequest_Request interface {
	isClientRequest_Request()
}

type ClientRequest_ListSources struct {
	ListSources *ListSourcesRequest `protobuf:"bytes,1,opt,name=list_sources,json=listSources,proto3,oneof"`
}

type ClientRequest_ListReadings struct {
	ListReadings *ListReadingsRequest `protobuf:"bytes,2,opt,name=list_readings,json=listReadings,proto3,oneof"`
}

type ClientRequest_SendCommand struct {
	SendCommand *SendCommandRequest `protobuf:"bytes,3,opt,name=send_command,json=sendCommand,proto3,oneof"`
}

func (*ClientRequest_ListSources) isClientRequest_Request() {}

func (*ClientRequest_ListReadings) isClientRequest_Request() {}

func (*ClientRequest_SendCommand) isClientRequest_Request() {}

type ClientResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*ClientResponse_ListSources
	//	*ClientResponse_ListReadings
	//	*ClientResponse_SendCommand
	Response      isClientResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientResponse) Reset() {
	*x = ClientResponse{}
	mi := &file_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResponse) ProtoMessage() {}

func (x *ClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResponse.ProtoReflect.Descriptor instead.
func (*ClientResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{1}
}

func (x *ClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClientResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClientResponse) GetResponse() isClientResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ClientResponse) GetListSources() *ListSourcesResponse {
	if x != nil {
		if x, ok := x.Response.(*ClientResponse_ListSources); ok {
			return x.ListSources
		}
	}
	return nil
}

func (x *ClientResponse) GetListReadings() *ListReadingsResponse {
	if x != nil {
		if x, ok := x.Response.(*ClientResponse_ListReadings); ok {
			return x.ListReadings
		}
	}
	return nil
}

func (x *ClientResponse) GetSendCommand() *SendCommandResponse {
	if x != nil {
		if x, ok := x.Response.(*ClientResponse_SendCommand); ok {
			return x.SendCommand
		}
	}
	return nil
}

type isClientResponse_Response interface {
	isClientResponse_Response()
}

type ClientResponse_ListSources struct {
	ListSources *ListSourcesResponse `protobuf:"bytes,3,opt,name=list_sources,json=listSources,proto3,oneof"`
}

type ClientResponse_ListReadings struct {
	ListReadings *ListReadingsResponse `protobuf:"bytes,4,opt,name=list_readings,json=listReadings,proto3,oneof"`
}

type ClientResponse_SendCommand struct {
	SendCommand *SendCommandResponse `protobuf:"bytes,5,opt,name=send_command,json=sendCommand,proto3,oneof"`
}

func (*ClientResponse_ListSources) isClientResponse_Response() {}

func (*ClientResponse_ListReadings) isClientResponse_Response() {}

func (*ClientResponse_SendCommand) isClientResponse_Response() {}

type ListSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSourcesRequest) Reset() {
	*x = ListSourcesRequest{}
	mi := &file_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourcesRequest) ProtoMessage() {}

func (x *ListSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourcesRequest.ProtoReflect.Descriptor instead.
func (*ListSourcesRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{2}
}

type SourceInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Ip             string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port           int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Controllable   bool                   `protobuf:"varint,5,opt,name=controllable,proto3" json:"controllable,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	LastSeenUnixMs int64                  `protobuf:"varint,7,opt,name=last_seen_unix_ms,json=lastSeenUnixMs,proto3" json:"last_seen_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SourceInfo) Reset() {
	*x = SourceInfo{}
	mi := &file_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceInfo) ProtoMessage() {}

func (x *SourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceInfo.ProtoReflect.Descriptor instead.
func (*SourceInfo) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{3}
}

func (x *SourceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SourceInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SourceInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SourceInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SourceInfo) GetControllable() bool {
	if x != nil {
		return x.Controllable
	}
	return false
}

func (x *SourceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SourceInfo) GetLastSeenUnixMs() int64 {
	if x != nil {
		return x.LastSeenUnixMs
	}
	return 0
}

type ListSourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*SourceInfo          `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSourcesResponse) Reset() {
	*x = ListSourcesResponse{}
	mi := &file_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourcesResponse) ProtoMessage() {}

func (x *ListSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListSourcesResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{4}
}

func (x *ListSourcesResponse) GetSources() []*SourceInfo {
	if x != nil {
		return x.Sources
	}
	return nil
}

type ListReadingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReadingsRequest) Reset() {
	*x = ListReadingsRequest{}
	mi := &file_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReadingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReadingsRequest) ProtoMessage() {}

func (x *ListReadingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReadingsRequest.ProtoReflect.Descriptor instead.
func (*ListReadingsRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{5}
}

func (x *ListReadingsRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

type ReadingInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceName      string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	SourceType      string                 `protobuf:"bytes,2,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Metric          string                 `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	Value           float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	Unit            string                 `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,6,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReadingInfo) Reset() {
	*x = ReadingInfo{}
	mi := &file_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadingInfo) ProtoMessage() {}

func (x *ReadingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadingInfo.ProtoReflect.Descriptor instead.
func (*ReadingInfo) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{6}
}

func (x *ReadingInfo) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *ReadingInfo) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *ReadingInfo) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *ReadingInfo) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ReadingInfo) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ReadingInfo) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type ListReadingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Readings      []*ReadingInfo         `protobuf:"bytes,1,rep,name=readings,proto3" json:"readings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReadingsResponse) Reset() {
	*x = ListReadingsResponse{}
	mi := &file_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReadingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReadingsResponse) ProtoMessage() {}

func (x *ListReadingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReadingsResponse.ProtoReflect.Descriptor instead.
func (*ListReadingsResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{7}
}

func (x *ListReadingsResponse) GetReadings() []*ReadingInfo {
	if x != nil {
		return x.Readings
	}
	return nil
}

type SendCommandRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SourceName string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*SendCommandRequest_Cam
	//	*SendCommandRequest_Lamppost
	//	*SendCommandRequest_Semaphore
	Command       isSendCommandRequest_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandRequest) Reset() {
	*x = SendCommandRequest{}
	mi := &file_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandRequest) ProtoMessage() {}

func (x *SendCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandRequest.ProtoReflect.Descriptor instead.
func (*SendCommandRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{8}
}

func (x *SendCommandRequest) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *SendCommandRequest) GetCommand() isSendCommandRequest_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *SendCommandRequest) GetCam() *CamCommand {
	if x != nil {
		if x, ok := x.Command.(*SendCommandRequest_Cam); ok {
			return x.Cam
		}
	}
	return nil
}

func (x *SendCommandRequest) GetLamppost() *LamppostCommand {
	if x != nil {
		if x, ok := x.Command.(*SendCommandRequest_Lamppost); ok {
			return x.Lamppost
		}
	}
	return nil
}

func (x *SendCommandRequest) GetSemaphore() *SemaphoreCommand {
	if x != nil {
		if x, ok := x.Command.(*SendCommandRequest_Semaphore); ok {
			return x.Semaphore
		}
	}
	return nil
}

type isSendCommandRequest_Command interface {
	isSendCommandRequest_Command()
}

type SendCommandRequest_Cam struct {
	Cam *CamCommand `protobuf:"bytes,2,opt,name=cam,proto3,oneof"`
}

type SendCommandRequest_Lamppost struct {
	Lamppost *LamppostCommand `protobuf:"bytes,3,opt,name=lamppost,proto3,oneof"`
}

type SendCommandRequest_Semaphore struct {
	Semaphore *SemaphoreCommand `protobuf:"bytes,4,opt,name=semaphore,proto3,oneof"`
}

func (*SendCommandRequest_Cam) isSendCommandRequest_Command() {}

func (*SendCommandRequest_Lamppost) isSendCommandRequest_Command() {}

func (*SendCommandRequest_Semaphore) isSendCommandRequest_Command() {}

type SendCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SourceStatus  string                 `protobuf:"bytes,3,opt,name=source_status,json=sourceStatus,proto3" json:"source_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandResponse) Reset() {
	*x = SendCommandResponse{}
	mi := &file_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandResponse) ProtoMessage() {}

func (x *SendCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandResponse.ProtoReflect.Descriptor instead.
func (*SendCommandResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{9}
}

func (x *SendCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendCommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendCommandResponse) GetSourceStatus() string {
	if x != nil {
		return x.SourceStatus
	}
	return ""
}

var File_client_proto protoreflect.FileDescriptor

const file_client_proto_rawDesc = "" +
	"\n" +
	"\fclient.proto\x12\x06client\x1a\tcam.proto\x1a\x0elamppost.proto\x1a\x0fsemaphore.proto\"\xe0\x01\n" +
	"\rClientRequest\x12?\n" +
	"\flist_sources\x18\x01 \x01(\v2\x1a.client.ListSourcesRequestH\x00R\vlistSources\x12B\n" +
	"\rlist_readings\x18\x02 \x01(\v2\x1b.client.ListReadingsRequestH\x00R\flistReadings\x12?\n" +
	"\fsend_command\x18\x03 \x01(\v2\x1a.client.SendCommandRequestH\x00R\vsendCommandB\t\n" +
	"\arequest\"\x99\x02\n" +
	"\x0eClientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12@\n" +
	"\flist_sources\x18\x03 \x01(\v2\x1b.client.ListSourcesResponseH\x00R\vlistSources\x12C\n" +
	"\rlist_readings\x18\x04 \x01(\v2\x1c.client.ListReadingsResponseH\x00R\flistReadings\x12@\n" +
	"\fsend_command\x18\x05 \x01(\v2\x1b.client.SendCommandResponseH\x00R\vsendCommandB\n" +
	"\n" +
	"\bresponse\"\x14\n" +
	"\x12ListSourcesRequest\"\xc5\x01\n" +
	"\n" +
	"SourceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\"\n" +
	"\fcontrollable\x18\x05 \x01(\bR\fcontrollable\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12)\n" +
	"\x11last_seen_unix_ms\x18\a \x01(\x03R\x0elastSeenUnixMs\"C\n" +
	"\x13ListSourcesResponse\x12,\n" +
	"\asources\x18\x01 \x03(\v2\x12.client.SourceInfoR\asources\"-\n" +
	"\x13ListReadingsRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\"\xbd\x01\n" +
	"\vReadingInfo\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12\x1f\n" +
	"\vsource_type\x18\x02 \x01(\tR\n" +
	"sourceType\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\tR\x06metric\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\x12*\n" +
	"\x11timestamp_unix_ms\x18\x06 \x01(\x03R\x0ftimestampUnixMs\"G\n" +
	"\x14ListReadingsResponse\x12/\n" +
	"\breadings\x18\x01 \x03(\v2\x13.client.ReadingInfoR\breadings\"\xdb\x01\n" +
	"\x12SendCommandRequest\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12#\n" +
	"\x03cam\x18\x02 \x01(\v2\x0f.cam.CamCommandH\x00R\x03cam\x127\n" +
	"\blamppost\x18\x03 \x01(\v2\x19.lamppost.LamppostCommandH\x00R\blamppost\x12;\n" +
	"\tsemaphore\x18\x04 \x01(\v2\x1b.semaphore.SemaphoreCommandH\x00R\tsemaphoreB\t\n" +
	"\acommand\"n\n" +
	"\x13SendCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rsource_status\x18\x03 \x01(\tR\fsourceStatusB>Z<github.com/cbysousa/distributed-systems/internal/proto;protob\x06proto3"

var (
	file_client_proto_rawDescOnce sync.Once
	file_client_proto_rawDescData []byte
)

func file_client_proto_rawDescGZIP() []byte {
	file_client_proto_rawDescOnce.Do(func() {
		file_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)))
	})
	return file_client_proto_rawDescData
}

var file_client_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_client_proto_goTypes = []any{
	(*ClientRequest)(nil),        // 0: client.ClientRequest
	(*ClientResponse)(nil),       // 1: client.ClientResponse
	(*ListSourcesRequest)(nil),   // 2: client.ListSourcesRequest
	(*SourceInfo)(nil),           // 3: client.SourceInfo
	(*ListSourcesResponse)(nil),  // 4: client.ListSourcesResponse
	(*ListReadingsRequest)(nil),  // 5: client.ListReadingsRequest
	(*ReadingInfo)(nil),          // 6: client.ReadingInfo
	(*ListReadingsResponse)(nil), // 7: client.ListReadingsResponse
	(*SendCommandRequest)(nil),   // 8: client.SendCommandRequest
	(*SendCommandResponse)(nil),  // 9: client.SendCommandResponse
	(*CamCommand)(nil),           // 10: cam.CamCommand
	(*LamppostCommand)(nil),      // 11: lamppost.LamppostCommand
	(*SemaphoreCommand)(nil),     // 12: semaphore.SemaphoreCommand
}
var file_client_proto_depIdxs = []int32{
	2,  // 0: client.ClientRequest.list_sources:type_name -> client.ListSourcesRequest
	5,  // 1: client.ClientRequest.list_readings:type_name -> client.ListReadingsRequest
	8,  // 2: client.ClientRequest.send_command:type_name -> client.SendCommandRequest
	4,  // 3: client.ClientResponse.list_sources:type_name -> client.ListSourcesResponse
	7,  // 4: client.ClientResponse.list_readings:type_name -> client.ListReadingsResponse
	9,  // 5: client.ClientResponse.send_command:type_name -> client.SendCommandResponse
	3,  // 6: client.ListSourcesResponse.sources:type_name -> client.SourceInfo
	6,  // 7: client.ListReadingsResponse.readings:type_name -> client.ReadingInfo
	10, // 8: client.SendCommandRequest.cam:type_name -> cam.CamCommand
	11, // 9: client.SendCommandRequest.lamppost:type_name -> lamppost.LamppostCommand
	12, // 10: client.SendCommandRequest.semaphore:type_name -> semaphore.SemaphoreCommand
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_client_proto_init() }
func file_client_proto_init() {
	if File_client_proto != nil {
		return
	}
	file_cam_proto_init()
	file_lamppost_proto_init()
	file_semaphore_proto_init()
	file_client_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientRequest_ListSources)(nil),
		(*ClientRequest_ListReadings)(nil),
		(*ClientRequest_SendCommand)(nil),
	}
	file_client_proto_msgTypes[1].OneofWrappers = []any{
		(*ClientResponse_ListSources)(nil),
		(*ClientResponse_ListReadings)(nil),
		(*ClientResponse_SendCommand)(nil),
	}
	file_client_proto_msgTypes[8].OneofWrappers = []any{
		(*SendCommandRequest_Cam)(nil),
		(*SendCommandRequest_Lamppost)(nil),
		(*SendCommandRequest_Semaphore)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_proto_goTypes,
		DependencyIndexes: file_client_proto_depIdxs,
		MessageInfos:      file_client_proto_msgTypes,
	}.Build()
	File_client_proto = out.File
	file_client_proto_goTypes = nil
	file_client_proto_depIdxs = nil
}
