// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: client.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AggregateOperation int32

const (
	AggregateOperation_AGGREGATE_OPERATION_AVG    AggregateOperation = 0
	AggregateOperation_AGGREGATE_OPERATION_STDDEV AggregateOperation = 1
	AggregateOperation_AGGREGATE_OPERATION_MIN    AggregateOperation = 2
	AggregateOperation_AGGREGATE_OPERATION_MAX    AggregateOperation = 3
)

// Enum value maps for AggregateOperation.
var (
	AggregateOperation_name = map[int32]string{
		0: "AGGREGATE_OPERATION_AVG",
		1: "AGGREGATE_OPERATION_STDDEV",
		2: "AGGREGATE_OPERATION_MIN",
		3: "AGGREGATE_OPERATION_MAX",
	}
	AggregateOperation_value = map[string]int32{
		"AGGREGATE_OPERATION_AVG":    0,
		"AGGREGATE_OPERATION_STDDEV": 1,
		"AGGREGATE_OPERATION_MIN":    2,
		"AGGREGATE_OPERATION_MAX":    3,
	}
)

func (x AggregateOperation) Enum() *AggregateOperation {
	p := new(AggregateOperation)
	*p = x
	return p
}

func (x AggregateOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AggregateOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_client_proto_enumTypes[0].Descriptor()
}

func (AggregateOperation) Type() protoreflect.EnumType {
	return &file_client_proto_enumTypes[0]
}

func (x AggregateOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AggregateOperation.Descriptor instead.
func (AggregateOperation) EnumDescriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

type ClientRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ClientRequest_ListSources
	//	*ClientRequest_ListReadings
	//	*ClientRequest_SendCommand
	//	*ClientRequest_Aggregate
	Request       isClientRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

func (x *ClientRequest) GetRequest() isClientRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ClientRequest) GetListSources() *ListSourcesRequest {
	if x != nil {
		if x, ok := x.Request.(*ClientRequest_ListSources); ok {
			return x.ListSources
		}
	}
	return nil
}

func (x *ClientRequest) GetListReadings() *ListReadingsRequest {
	if x != nil {
		if x, ok := x.Request.(*ClientRequest_ListReadings); ok {
			return x.ListReadings
		}
	}
	return nil
}

func (x *ClientRequest) GetSendCommand() *SendCommandRequest {
	if x != nil {
		if x, ok := x.Request.(*ClientRequest_SendCommand); ok {
			return x.SendCommand
		}
	}
	return nil
}

func (x *ClientRequest) GetAggregate() *AggregateRequest {
	if x != nil {
		if x, ok := x.Request.(*ClientRequest_Aggregate); ok {
			return x.Aggregate
		}
	}
	return nil
}

type isClientRequest_Request interface {
	isClientRequest_Request()
}

type ClientRequest_ListSources struct {
	ListSources *ListSourcesRequest `protobuf:"bytes,1,opt,name=list_sources,json=listSources,proto3,oneof"`
}

type ClientRequest_ListReadings struct {
	ListReadings *ListReadingsRequest `protobuf:"bytes,2,opt,name=list_readings,json=listReadings,proto3,oneof"`
}

type ClientRequest_SendCommand struct {
	SendCommand *SendCommandRequest `protobuf:"bytes,3,opt,name=send_command,json=sendCommand,proto3,oneof"`
}

type ClientRequest_Aggregate struct {
	Aggregate *AggregateRequest `protobuf:"bytes,4,opt,name=aggregate,proto3,oneof"`
}

func (*ClientRequest_ListSources) isClientRequest_Request() {}

func (*ClientRequest_ListReadings) isClientRequest_Request() {}

func (*ClientRequest_SendCommand) isClientRequest_Request() {}

func (*ClientRequest_Aggregate) isClientRequest_Request() {}

type ClientResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*ClientResponse_ListSources
	//	*ClientResponse_ListReadings
	//	*ClientResponse_SendCommand
	//	*ClientResponse_Aggregate
	Response      isClientResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientResponse) Reset() {
	*x = ClientResponse{}
	mi := &file_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResponse) ProtoMessage() {}

func (x *ClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResponse.ProtoReflect.Descriptor instead.
func (*ClientResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{1}
}

func (x *ClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClientResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ClientResponse) GetResponse() isClientResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ClientResponse) GetListSources() *ListSourcesResponse {
	if x != nil {
		if x, ok := x.Response.(*ClientResponse_ListSources); ok {
			return x.ListSources
		}
	}
	return nil
}

func (x *ClientResponse) GetListReadings() *ListReadingsResponse {
	if x != nil {
		if x, ok := x.Response.(*ClientResponse_ListReadings); ok {
			return x.ListReadings
		}
	}
	return nil
}

func (x *ClientResponse) GetSendCommand() *SendCommandResponse {
	if x != nil {
		if x, ok := x.Response.(*ClientResponse_SendCommand); ok {
			return x.SendCommand
		}
	}
	return nil
}

func (x *ClientResponse) GetAggregate() *AggregateResponse {
	if x != nil {
		if x, ok := x.Response.(*ClientResponse_Aggregate); ok {
			return x.Aggregate
		}
	}
	return nil
}

type isClientResponse_Response interface {
	isClientResponse_Response()
}

type ClientResponse_ListSources struct {
	ListSources *ListSourcesResponse `protobuf:"bytes,3,opt,name=list_sources,json=listSources,proto3,oneof"`
}

type ClientResponse_ListReadings struct {
	ListReadings *ListReadingsResponse `protobuf:"bytes,4,opt,name=list_readings,json=listReadings,proto3,oneof"`
}

type ClientResponse_SendCommand struct {
	SendCommand *SendCommandResponse `protobuf:"bytes,5,opt,name=send_command,json=sendCommand,proto3,oneof"`
}

type ClientResponse_Aggregate struct {
	Aggregate *AggregateResponse `protobuf:"bytes,6,opt,name=aggregate,proto3,oneof"`
}

func (*ClientResponse_ListSources) isClientResponse_Response() {}

func (*ClientResponse_ListReadings) isClientResponse_Response() {}

func (*ClientResponse_SendCommand) isClientResponse_Response() {}

func (*ClientResponse_Aggregate) isClientResponse_Response() {}

type ListSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSourcesRequest) Reset() {
	*x = ListSourcesRequest{}
	mi := &file_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourcesRequest) ProtoMessage() {}

func (x *ListSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourcesRequest.ProtoReflect.Descriptor instead.
func (*ListSourcesRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{2}
}

type SourceInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Ip             string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port           int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Controllable   bool                   `protobuf:"varint,5,opt,name=controllable,proto3" json:"controllable,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	LastSeenUnixMs int64                  `protobuf:"varint,7,opt,name=last_seen_unix_ms,json=lastSeenUnixMs,proto3" json:"last_seen_unix_ms,omitempty"`
	SourceType     string                 `protobuf:"bytes,8,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SourceInfo) Reset() {
	*x = SourceInfo{}
	mi := &file_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceInfo) ProtoMessage() {}

func (x *SourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceInfo.ProtoReflect.Descriptor instead.
func (*SourceInfo) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{3}
}

func (x *SourceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SourceInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SourceInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SourceInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SourceInfo) GetControllable() bool {
	if x != nil {
		return x.Controllable
	}
	return false
}

func (x *SourceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SourceInfo) GetLastSeenUnixMs() int64 {
	if x != nil {
		return x.LastSeenUnixMs
	}
	return 0
}

func (x *SourceInfo) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

type ListSourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*SourceInfo          `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSourcesResponse) Reset() {
	*x = ListSourcesResponse{}
	mi := &file_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourcesResponse) ProtoMessage() {}

func (x *ListSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListSourcesResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{4}
}

func (x *ListSourcesResponse) GetSources() []*SourceInfo {
	if x != nil {
		return x.Sources
	}
	return nil
}

type ListReadingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReadingsRequest) Reset() {
	*x = ListReadingsRequest{}
	mi := &file_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReadingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReadingsRequest) ProtoMessage() {}

func (x *ListReadingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReadingsRequest.ProtoReflect.Descriptor instead.
func (*ListReadingsRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{5}
}

type ReadingInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceName      string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	SourceType      string                 `protobuf:"bytes,2,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Metric          string                 `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	Value           float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	Unit            string                 `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,6,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReadingInfo) Reset() {
	*x = ReadingInfo{}
	mi := &file_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadingInfo) ProtoMessage() {}

func (x *ReadingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadingInfo.ProtoReflect.Descriptor instead.
func (*ReadingInfo) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{6}
}

func (x *ReadingInfo) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *ReadingInfo) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *ReadingInfo) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *ReadingInfo) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ReadingInfo) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ReadingInfo) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type ListReadingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Readings      []*ReadingInfo         `protobuf:"bytes,1,rep,name=readings,proto3" json:"readings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReadingsResponse) Reset() {
	*x = ListReadingsResponse{}
	mi := &file_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReadingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReadingsResponse) ProtoMessage() {}

func (x *ListReadingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReadingsResponse.ProtoReflect.Descriptor instead.
func (*ListReadingsResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{7}
}

func (x *ListReadingsResponse) GetReadings() []*ReadingInfo {
	if x != nil {
		return x.Readings
	}
	return nil
}

type SendCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceName    string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	Lamppost      *LamppostCommand       `protobuf:"bytes,2,opt,name=lamppost,proto3" json:"lamppost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandRequest) Reset() {
	*x = SendCommandRequest{}
	mi := &file_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandRequest) ProtoMessage() {}

func (x *SendCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandRequest.ProtoReflect.Descriptor instead.
func (*SendCommandRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{8}
}

func (x *SendCommandRequest) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *SendCommandRequest) GetLamppost() *LamppostCommand {
	if x != nil {
		return x.Lamppost
	}
	return nil
}

type SendCommandResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SourceStatus      string                 `protobuf:"bytes,3,opt,name=source_status,json=sourceStatus,proto3" json:"source_status,omitempty"`
	LuminosityPercent float64                `protobuf:"fixed64,4,opt,name=luminosity_percent,json=luminosityPercent,proto3" json:"luminosity_percent,omitempty"`
	LightOn           bool                   `protobuf:"varint,5,opt,name=light_on,json=lightOn,proto3" json:"light_on,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SendCommandResponse) Reset() {
	*x = SendCommandResponse{}
	mi := &file_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandResponse) ProtoMessage() {}

func (x *SendCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandResponse.ProtoReflect.Descriptor instead.
func (*SendCommandResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{9}
}

func (x *SendCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendCommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendCommandResponse) GetSourceStatus() string {
	if x != nil {
		return x.SourceStatus
	}
	return ""
}

func (x *SendCommandResponse) GetLuminosityPercent() float64 {
	if x != nil {
		return x.LuminosityPercent
	}
	return 0
}

func (x *SendCommandResponse) GetLightOn() bool {
	if x != nil {
		return x.LightOn
	}
	return false
}

type AggregateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceName    string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	Metric        string                 `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	Operation     AggregateOperation     `protobuf:"varint,3,opt,name=operation,proto3,enum=client.AggregateOperation" json:"operation,omitempty"`
	WindowSeconds int64                  `protobuf:"varint,4,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateRequest) Reset() {
	*x = AggregateRequest{}
	mi := &file_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateRequest) ProtoMessage() {}

func (x *AggregateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateRequest.ProtoReflect.Descriptor instead.
func (*AggregateRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{10}
}

func (x *AggregateRequest) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *AggregateRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *AggregateRequest) GetOperation() AggregateOperation {
	if x != nil {
		return x.Operation
	}
	return AggregateOperation_AGGREGATE_OPERATION_AVG
}

func (x *AggregateRequest) GetWindowSeconds() int64 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

type AggregateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceName    string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	Metric        string                 `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	Operation     AggregateOperation     `protobuf:"varint,3,opt,name=operation,proto3,enum=client.AggregateOperation" json:"operation,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	SampleCount   int32                  `protobuf:"varint,5,opt,name=sample_count,json=sampleCount,proto3" json:"sample_count,omitempty"`
	WindowSeconds int64                  `protobuf:"varint,6,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	Unit          string                 `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregateResponse) Reset() {
	*x = AggregateResponse{}
	mi := &file_client_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateResponse) ProtoMessage() {}

func (x *AggregateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateResponse.ProtoReflect.Descriptor instead.
func (*AggregateResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{11}
}

func (x *AggregateResponse) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *AggregateResponse) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *AggregateResponse) GetOperation() AggregateOperation {
	if x != nil {
		return x.Operation
	}
	return AggregateOperation_AGGREGATE_OPERATION_AVG
}

func (x *AggregateResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AggregateResponse) GetSampleCount() int32 {
	if x != nil {
		return x.SampleCount
	}
	return 0
}

func (x *AggregateResponse) GetWindowSeconds() int64 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

func (x *AggregateResponse) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

var File_client_proto protoreflect.FileDescriptor

const file_client_proto_rawDesc = "" +
	"\n" +
	"\fclient.proto\x12\x06client\x1a\x0elamppost.proto\"\x9a\x02\n" +
	"\rClientRequest\x12?\n" +
	"\flist_sources\x18\x01 \x01(\v2\x1a.client.ListSourcesRequestH\x00R\vlistSources\x12B\n" +
	"\rlist_readings\x18\x02 \x01(\v2\x1b.client.ListReadingsRequestH\x00R\flistReadings\x12?\n" +
	"\fsend_command\x18\x03 \x01(\v2\x1a.client.SendCommandRequestH\x00R\vsendCommand\x128\n" +
	"\taggregate\x18\x04 \x01(\v2\x18.client.AggregateRequestH\x00R\taggregateB\t\n" +
	"\arequest\"\xd4\x02\n" +
	"\x0eClientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12@\n" +
	"\flist_sources\x18\x03 \x01(\v2\x1b.client.ListSourcesResponseH\x00R\vlistSources\x12C\n" +
	"\rlist_readings\x18\x04 \x01(\v2\x1c.client.ListReadingsResponseH\x00R\flistReadings\x12@\n" +
	"\fsend_command\x18\x05 \x01(\v2\x1b.client.SendCommandResponseH\x00R\vsendCommand\x129\n" +
	"\taggregate\x18\x06 \x01(\v2\x19.client.AggregateResponseH\x00R\taggregateB\n" +
	"\n" +
	"\bresponse\"\x14\n" +
	"\x12ListSourcesRequest\"\xe6\x01\n" +
	"\n" +
	"SourceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\"\n" +
	"\fcontrollable\x18\x05 \x01(\bR\fcontrollable\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12)\n" +
	"\x11last_seen_unix_ms\x18\a \x01(\x03R\x0elastSeenUnixMs\x12\x1f\n" +
	"\vsource_type\x18\b \x01(\tR\n" +
	"sourceType\"C\n" +
	"\x13ListSourcesResponse\x12,\n" +
	"\asources\x18\x01 \x03(\v2\x12.client.SourceInfoR\asources\"\x15\n" +
	"\x13ListReadingsRequest\"\xbd\x01\n" +
	"\vReadingInfo\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12\x1f\n" +
	"\vsource_type\x18\x02 \x01(\tR\n" +
	"sourceType\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\tR\x06metric\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\x12*\n" +
	"\x11timestamp_unix_ms\x18\x06 \x01(\x03R\x0ftimestampUnixMs\"G\n" +
	"\x14ListReadingsResponse\x12/\n" +
	"\breadings\x18\x01 \x03(\v2\x13.client.ReadingInfoR\breadings\"l\n" +
	"\x12SendCommandRequest\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x125\n" +
	"\blamppost\x18\x02 \x01(\v2\x19.lamppost.LamppostCommandR\blamppost\"\xb8\x01\n" +
	"\x13SendCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rsource_status\x18\x03 \x01(\tR\fsourceStatus\x12-\n" +
	"\x12luminosity_percent\x18\x04 \x01(\x01R\x11luminosityPercent\x12\x19\n" +
	"\blight_on\x18\x05 \x01(\bR\alightOn\"\xac\x01\n" +
	"\x10AggregateRequest\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\x128\n" +
	"\toperation\x18\x03 \x01(\x0e2\x1a.client.AggregateOperationR\toperation\x12%\n" +
	"\x0ewindow_seconds\x18\x04 \x01(\x03R\rwindowSeconds\"\xfa\x01\n" +
	"\x11AggregateResponse\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\x128\n" +
	"\toperation\x18\x03 \x01(\x0e2\x1a.client.AggregateOperationR\toperation\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12!\n" +
	"\fsample_count\x18\x05 \x01(\x05R\vsampleCount\x12%\n" +
	"\x0ewindow_seconds\x18\x06 \x01(\x03R\rwindowSeconds\x12\x12\n" +
	"\x04unit\x18\a \x01(\tR\x04unit*\x8b\x01\n" +
	"\x12AggregateOperation\x12\x1b\n" +
	"\x17AGGREGATE_OPERATION_AVG\x10\x00\x12\x1e\n" +
	"\x1aAGGREGATE_OPERATION_STDDEV\x10\x01\x12\x1b\n" +
	"\x17AGGREGATE_OPERATION_MIN\x10\x02\x12\x1b\n" +
	"\x17AGGREGATE_OPERATION_MAX\x10\x03B>Z<github.com/cbysousa/distributed-systems/internal/proto;protob\x06proto3"

var (
	file_client_proto_rawDescOnce sync.Once
	file_client_proto_rawDescData []byte
)

func file_client_proto_rawDescGZIP() []byte {
	file_client_proto_rawDescOnce.Do(func() {
		file_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)))
	})
	return file_client_proto_rawDescData
}

var file_client_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_client_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_client_proto_goTypes = []any{
	(AggregateOperation)(0),      // 0: client.AggregateOperation
	(*ClientRequest)(nil),        // 1: client.ClientRequest
	(*ClientResponse)(nil),       // 2: client.ClientResponse
	(*ListSourcesRequest)(nil),   // 3: client.ListSourcesRequest
	(*SourceInfo)(nil),           // 4: client.SourceInfo
	(*ListSourcesResponse)(nil),  // 5: client.ListSourcesResponse
	(*ListReadingsRequest)(nil),  // 6: client.ListReadingsRequest
	(*ReadingInfo)(nil),          // 7: client.ReadingInfo
	(*ListReadingsResponse)(nil), // 8: client.ListReadingsResponse
	(*SendCommandRequest)(nil),   // 9: client.SendCommandRequest
	(*SendCommandResponse)(nil),  // 10: client.SendCommandResponse
	(*AggregateRequest)(nil),     // 11: client.AggregateRequest
	(*AggregateResponse)(nil),    // 12: client.AggregateResponse
	(*LamppostCommand)(nil),      // 13: lamppost.LamppostCommand
}
var file_client_proto_depIdxs = []int32{
	3,  // 0: client.ClientRequest.list_sources:type_name -> client.ListSourcesRequest
	6,  // 1: client.ClientRequest.list_readings:type_name -> client.ListReadingsRequest
	9,  // 2: client.ClientRequest.send_command:type_name -> client.SendCommandRequest
	11, // 3: client.ClientRequest.aggregate:type_name -> client.AggregateRequest
	5,  // 4: client.ClientResponse.list_sources:type_name -> client.ListSourcesResponse
	8,  // 5: client.ClientResponse.list_readings:type_name -> client.ListReadingsResponse
	10, // 6: client.ClientResponse.send_command:type_name -> client.SendCommandResponse
	12, // 7: client.ClientResponse.aggregate:type_name -> client.AggregateResponse
	4,  // 8: client.ListSourcesResponse.sources:type_name -> client.SourceInfo
	7,  // 9: client.ListReadingsResponse.readings:type_name -> client.ReadingInfo
	13, // 10: client.SendCommandRequest.lamppost:type_name -> lamppost.LamppostCommand
	0,  // 11: client.AggregateRequest.operation:type_name -> client.AggregateOperation
	0,  // 12: client.AggregateResponse.operation:type_name -> client.AggregateOperation
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_client_proto_init() }
func file_client_proto_init() {
	if File_client_proto != nil {
		return
	}
	file_lamppost_proto_init()
	file_client_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientRequest_ListSources)(nil),
		(*ClientRequest_ListReadings)(nil),
		(*ClientRequest_SendCommand)(nil),
		(*ClientRequest_Aggregate)(nil),
	}
	file_client_proto_msgTypes[1].OneofWrappers = []any{
		(*ClientResponse_ListSources)(nil),
		(*ClientResponse_ListReadings)(nil),
		(*ClientResponse_SendCommand)(nil),
		(*ClientResponse_Aggregate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_proto_goTypes,
		DependencyIndexes: file_client_proto_depIdxs,
		EnumInfos:         file_client_proto_enumTypes,
		MessageInfos:      file_client_proto_msgTypes,
	}.Build()
	File_client_proto = out.File
	file_client_proto_goTypes = nil
	file_client_proto_depIdxs = nil
}
