// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: lamppost.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LamppostCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*LamppostCommand_TurnOn
	//	*LamppostCommand_TurnOff
	//	*LamppostCommand_GetState
	//	*LamppostCommand_SimulateFailure
	Command       isLamppostCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LamppostCommand) Reset() {
	*x = LamppostCommand{}
	mi := &file_lamppost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LamppostCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LamppostCommand) ProtoMessage() {}

func (x *LamppostCommand) ProtoReflect() protoreflect.Message {
	mi := &file_lamppost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LamppostCommand.ProtoReflect.Descriptor instead.
func (*LamppostCommand) Descriptor() ([]byte, []int) {
	return file_lamppost_proto_rawDescGZIP(), []int{0}
}

func (x *LamppostCommand) GetCommand() isLamppostCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *LamppostCommand) GetTurnOn() *LamppostTurnOnRequest {
	if x != nil {
		if x, ok := x.Command.(*LamppostCommand_TurnOn); ok {
			return x.TurnOn
		}
	}
	return nil
}

func (x *LamppostCommand) GetTurnOff() *LamppostTurnOffRequest {
	if x != nil {
		if x, ok := x.Command.(*LamppostCommand_TurnOff); ok {
			return x.TurnOff
		}
	}
	return nil
}

func (x *LamppostCommand) GetGetState() *LamppostGetStateRequest {
	if x != nil {
		if x, ok := x.Command.(*LamppostCommand_GetState); ok {
			return x.GetState
		}
	}
	return nil
}

func (x *LamppostCommand) GetSimulateFailure() *LamppostSimulateFailureRequest {
	if x != nil {
		if x, ok := x.Command.(*LamppostCommand_SimulateFailure); ok {
			return x.SimulateFailure
		}
	}
	return nil
}

type isLamppostCommand_Command interface {
	isLamppostCommand_Command()
}

type LamppostCommand_TurnOn struct {
	TurnOn *LamppostTurnOnRequest `protobuf:"bytes,1,opt,name=turn_on,json=turnOn,proto3,oneof"`
}

type LamppostCommand_TurnOff struct {
	TurnOff *LamppostTurnOffRequest `protobuf:"bytes,2,opt,name=turn_off,json=turnOff,proto3,oneof"`
}

type LamppostCommand_GetState struct {
	GetState *LamppostGetStateRequest `protobuf:"bytes,3,opt,name=get_state,json=getState,proto3,oneof"`
}

type LamppostCommand_SimulateFailure struct {
	SimulateFailure *LamppostSimulateFailureRequest `protobuf:"bytes,4,opt,name=simulate_failure,json=simulateFailure,proto3,oneof"`
}

func (*LamppostCommand_TurnOn) isLamppostCommand_Command() {}

func (*LamppostCommand_TurnOff) isLamppostCommand_Command() {}

func (*LamppostCommand_GetState) isLamppostCommand_Command() {}

func (*LamppostCommand_SimulateFailure) isLamppostCommand_Command() {}

type LamppostTurnOnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LamppostTurnOnRequest) Reset() {
	*x = LamppostTurnOnRequest{}
	mi := &file_lamppost_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LamppostTurnOnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LamppostTurnOnRequest) ProtoMessage() {}

func (x *LamppostTurnOnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lamppost_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LamppostTurnOnRequest.ProtoReflect.Descriptor instead.
func (*LamppostTurnOnRequest) Descriptor() ([]byte, []int) {
	return file_lamppost_proto_rawDescGZIP(), []int{1}
}

type LamppostTurnOffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LamppostTurnOffRequest) Reset() {
	*x = LamppostTurnOffRequest{}
	mi := &file_lamppost_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LamppostTurnOffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LamppostTurnOffRequest) ProtoMessage() {}

func (x *LamppostTurnOffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lamppost_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LamppostTurnOffRequest.ProtoReflect.Descriptor instead.
func (*LamppostTurnOffRequest) Descriptor() ([]byte, []int) {
	return file_lamppost_proto_rawDescGZIP(), []int{2}
}

type LamppostGetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LamppostGetStateRequest) Reset() {
	*x = LamppostGetStateRequest{}
	mi := &file_lamppost_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LamppostGetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LamppostGetStateRequest) ProtoMessage() {}

func (x *LamppostGetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lamppost_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LamppostGetStateRequest.ProtoReflect.Descriptor instead.
func (*LamppostGetStateRequest) Descriptor() ([]byte, []int) {
	return file_lamppost_proto_rawDescGZIP(), []int{3}
}

type LamppostSimulateFailureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LamppostSimulateFailureRequest) Reset() {
	*x = LamppostSimulateFailureRequest{}
	mi := &file_lamppost_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LamppostSimulateFailureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LamppostSimulateFailureRequest) ProtoMessage() {}

func (x *LamppostSimulateFailureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lamppost_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LamppostSimulateFailureRequest.ProtoReflect.Descriptor instead.
func (*LamppostSimulateFailureRequest) Descriptor() ([]byte, []int) {
	return file_lamppost_proto_rawDescGZIP(), []int{4}
}

type LamppostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LamppostResponse) Reset() {
	*x = LamppostResponse{}
	mi := &file_lamppost_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LamppostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LamppostResponse) ProtoMessage() {}

func (x *LamppostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lamppost_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LamppostResponse.ProtoReflect.Descriptor instead.
func (*LamppostResponse) Descriptor() ([]byte, []int) {
	return file_lamppost_proto_rawDescGZIP(), []int{5}
}

func (x *LamppostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LamppostResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LamppostResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *LamppostResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_lamppost_proto protoreflect.FileDescriptor

const file_lamppost_proto_rawDesc = "" +
	"\n" +
	"\x0elamppost.proto\x12\blamppost\"\xb0\x02\n" +
	"\x0fLamppostCommand\x12:\n" +
	"\aturn_on\x18\x01 \x01(\v2\x1f.lamppost.LamppostTurnOnRequestH\x00R\x06turnOn\x12=\n" +
	"\bturn_off\x18\x02 \x01(\v2 .lamppost.LamppostTurnOffRequestH\x00R\aturnOff\x12@\n" +
	"\tget_state\x18\x03 \x01(\v2!.lamppost.LamppostGetStateRequestH\x00R\bgetState\x12U\n" +
	"\x10simulate_failure\x18\x04 \x01(\v2(.lamppost.LamppostSimulateFailureRequestH\x00R\x0fsimulateFailureB\t\n" +
	"\acommand\"\x17\n" +
	"\x15LamppostTurnOnRequest\"\x18\n" +
	"\x16LamppostTurnOffRequest\"\x19\n" +
	"\x17LamppostGetStateRequest\" \n" +
	"\x1eLamppostSimulateFailureRequest\"v\n" +
	"\x10LamppostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06statusB>Z<github.com/cbysousa/distributed-systems/internal/proto;protob\x06proto3"

var (
	file_lamppost_proto_rawDescOnce sync.Once
	file_lamppost_proto_rawDescData []byte
)

func file_lamppost_proto_rawDescGZIP() []byte {
	file_lamppost_proto_rawDescOnce.Do(func() {
		file_lamppost_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lamppost_proto_rawDesc), len(file_lamppost_proto_rawDesc)))
	})
	return file_lamppost_proto_rawDescData
}

var file_lamppost_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_lamppost_proto_goTypes = []any{
	(*LamppostCommand)(nil),                // 0: lamppost.LamppostCommand
	(*LamppostTurnOnRequest)(nil),          // 1: lamppost.LamppostTurnOnRequest
	(*LamppostTurnOffRequest)(nil),         // 2: lamppost.LamppostTurnOffRequest
	(*LamppostGetStateRequest)(nil),        // 3: lamppost.LamppostGetStateRequest
	(*LamppostSimulateFailureRequest)(nil), // 4: lamppost.LamppostSimulateFailureRequest
	(*LamppostResponse)(nil),               // 5: lamppost.LamppostResponse
}
var file_lamppost_proto_depIdxs = []int32{
	1, // 0: lamppost.LamppostCommand.turn_on:type_name -> lamppost.LamppostTurnOnRequest
	2, // 1: lamppost.LamppostCommand.turn_off:type_name -> lamppost.LamppostTurnOffRequest
	3, // 2: lamppost.LamppostCommand.get_state:type_name -> lamppost.LamppostGetStateRequest
	4, // 3: lamppost.LamppostCommand.simulate_failure:type_name -> lamppost.LamppostSimulateFailureRequest
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_lamppost_proto_init() }
func file_lamppost_proto_init() {
	if File_lamppost_proto != nil {
		return
	}
	file_lamppost_proto_msgTypes[0].OneofWrappers = []any{
		(*LamppostCommand_TurnOn)(nil),
		(*LamppostCommand_TurnOff)(nil),
		(*LamppostCommand_GetState)(nil),
		(*LamppostCommand_SimulateFailure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lamppost_proto_rawDesc), len(file_lamppost_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lamppost_proto_goTypes,
		DependencyIndexes: file_lamppost_proto_depIdxs,
		MessageInfos:      file_lamppost_proto_msgTypes,
	}.Build()
	File_lamppost_proto = out.File
	file_lamppost_proto_goTypes = nil
	file_lamppost_proto_depIdxs = nil
}
