// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: readings.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadingPacket struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceName      string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,2,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	// Types that are valid to be assigned to Reading:
	//
	//	*ReadingPacket_Temperature
	//	*ReadingPacket_AirQuality
	Reading       isReadingPacket_Reading `protobuf_oneof:"reading"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadingPacket) Reset() {
	*x = ReadingPacket{}
	mi := &file_readings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadingPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadingPacket) ProtoMessage() {}

func (x *ReadingPacket) ProtoReflect() protoreflect.Message {
	mi := &file_readings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadingPacket.ProtoReflect.Descriptor instead.
func (*ReadingPacket) Descriptor() ([]byte, []int) {
	return file_readings_proto_rawDescGZIP(), []int{0}
}

func (x *ReadingPacket) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *ReadingPacket) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *ReadingPacket) GetReading() isReadingPacket_Reading {
	if x != nil {
		return x.Reading
	}
	return nil
}

func (x *ReadingPacket) GetTemperature() *TemperatureReading {
	if x != nil {
		if x, ok := x.Reading.(*ReadingPacket_Temperature); ok {
			return x.Temperature
		}
	}
	return nil
}

func (x *ReadingPacket) GetAirQuality() *AirQualityReading {
	if x != nil {
		if x, ok := x.Reading.(*ReadingPacket_AirQuality); ok {
			return x.AirQuality
		}
	}
	return nil
}

type isReadingPacket_Reading interface {
	isReadingPacket_Reading()
}

type ReadingPacket_Temperature struct {
	Temperature *TemperatureReading `protobuf:"bytes,3,opt,name=temperature,proto3,oneof"`
}

type ReadingPacket_AirQuality struct {
	AirQuality *AirQualityReading `protobuf:"bytes,4,opt,name=air_quality,json=airQuality,proto3,oneof"`
}

func (*ReadingPacket_Temperature) isReadingPacket_Reading() {}

func (*ReadingPacket_AirQuality) isReadingPacket_Reading() {}

var File_readings_proto protoreflect.FileDescriptor

const file_readings_proto_rawDesc = "" +
	"\n" +
	"\x0ereadings.proto\x12\breadings\x1a\x11temperature.proto\x1a\x11air_quality.proto\"\xee\x01\n" +
	"\rReadingPacket\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12*\n" +
	"\x11timestamp_unix_ms\x18\x02 \x01(\x03R\x0ftimestampUnixMs\x12C\n" +
	"\vtemperature\x18\x03 \x01(\v2\x1f.temperature.TemperatureReadingH\x00R\vtemperature\x12@\n" +
	"\vair_quality\x18\x04 \x01(\v2\x1d.airquality.AirQualityReadingH\x00R\n" +
	"airQualityB\t\n" +
	"\areadingB>Z<github.com/cbysousa/distributed-systems/internal/proto;protob\x06proto3"

var (
	file_readings_proto_rawDescOnce sync.Once
	file_readings_proto_rawDescData []byte
)

func file_readings_proto_rawDescGZIP() []byte {
	file_readings_proto_rawDescOnce.Do(func() {
		file_readings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_readings_proto_rawDesc), len(file_readings_proto_rawDesc)))
	})
	return file_readings_proto_rawDescData
}

var file_readings_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_readings_proto_goTypes = []any{
	(*ReadingPacket)(nil),      // 0: readings.ReadingPacket
	(*TemperatureReading)(nil), // 1: temperature.TemperatureReading
	(*AirQualityReading)(nil),  // 2: airquality.AirQualityReading
}
var file_readings_proto_depIdxs = []int32{
	1, // 0: readings.ReadingPacket.temperature:type_name -> temperature.TemperatureReading
	2, // 1: readings.ReadingPacket.air_quality:type_name -> airquality.AirQualityReading
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_readings_proto_init() }
func file_readings_proto_init() {
	if File_readings_proto != nil {
		return
	}
	file_temperature_proto_init()
	file_air_quality_proto_init()
	file_readings_proto_msgTypes[0].OneofWrappers = []any{
		(*ReadingPacket_Temperature)(nil),
		(*ReadingPacket_AirQuality)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_readings_proto_rawDesc), len(file_readings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_readings_proto_goTypes,
		DependencyIndexes: file_readings_proto_depIdxs,
		MessageInfos:      file_readings_proto_msgTypes,
	}.Build()
	File_readings_proto = out.File
	file_readings_proto_goTypes = nil
	file_readings_proto_depIdxs = nil
}
