// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: semaphore.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SemaphoreState int32

const (
	SemaphoreState_SEMAPHORE_STATE_RED    SemaphoreState = 0
	SemaphoreState_SEMAPHORE_STATE_YELLOW SemaphoreState = 1
	SemaphoreState_SEMAPHORE_STATE_GREEN  SemaphoreState = 2
)

// Enum value maps for SemaphoreState.
var (
	SemaphoreState_name = map[int32]string{
		0: "SEMAPHORE_STATE_RED",
		1: "SEMAPHORE_STATE_YELLOW",
		2: "SEMAPHORE_STATE_GREEN",
	}
	SemaphoreState_value = map[string]int32{
		"SEMAPHORE_STATE_RED":    0,
		"SEMAPHORE_STATE_YELLOW": 1,
		"SEMAPHORE_STATE_GREEN":  2,
	}
)

func (x SemaphoreState) Enum() *SemaphoreState {
	p := new(SemaphoreState)
	*p = x
	return p
}

func (x SemaphoreState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SemaphoreState) Descriptor() protoreflect.EnumDescriptor {
	return file_semaphore_proto_enumTypes[0].Descriptor()
}

func (SemaphoreState) Type() protoreflect.EnumType {
	return &file_semaphore_proto_enumTypes[0]
}

func (x SemaphoreState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SemaphoreState.Descriptor instead.
func (SemaphoreState) EnumDescriptor() ([]byte, []int) {
	return file_semaphore_proto_rawDescGZIP(), []int{0}
}

type SemaphoreCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*SemaphoreCommand_ChangeState
	//	*SemaphoreCommand_GetState
	//	*SemaphoreCommand_SetTimer
	//	*SemaphoreCommand_SimulateFailure
	Command       isSemaphoreCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemaphoreCommand) Reset() {
	*x = SemaphoreCommand{}
	mi := &file_semaphore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemaphoreCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemaphoreCommand) ProtoMessage() {}

func (x *SemaphoreCommand) ProtoReflect() protoreflect.Message {
	mi := &file_semaphore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemaphoreCommand.ProtoReflect.Descriptor instead.
func (*SemaphoreCommand) Descriptor() ([]byte, []int) {
	return file_semaphore_proto_rawDescGZIP(), []int{0}
}

func (x *SemaphoreCommand) GetCommand() isSemaphoreCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *SemaphoreCommand) GetChangeState() *SemaphoreChangeStateRequest {
	if x != nil {
		if x, ok := x.Command.(*SemaphoreCommand_ChangeState); ok {
			return x.ChangeState
		}
	}
	return nil
}

func (x *SemaphoreCommand) GetGetState() *SemaphoreGetStateRequest {
	if x != nil {
		if x, ok := x.Command.(*SemaphoreCommand_GetState); ok {
			return x.GetState
		}
	}
	return nil
}

func (x *SemaphoreCommand) GetSetTimer() *SemaphoreSetTimerRequest {
	if x != nil {
		if x, ok := x.Command.(*SemaphoreCommand_SetTimer); ok {
			return x.SetTimer
		}
	}
	return nil
}

func (x *SemaphoreCommand) GetSimulateFailure() *SemaphoreSimulateFailureRequest {
	if x != nil {
		if x, ok := x.Command.(*SemaphoreCommand_SimulateFailure); ok {
			return x.SimulateFailure
		}
	}
	return nil
}

type isSemaphoreCommand_Command interface {
	isSemaphoreCommand_Command()
}

type SemaphoreCommand_ChangeState struct {
	ChangeState *SemaphoreChangeStateRequest `protobuf:"bytes,1,opt,name=change_state,json=changeState,proto3,oneof"`
}

type SemaphoreCommand_GetState struct {
	GetState *SemaphoreGetStateRequest `protobuf:"bytes,2,opt,name=get_state,json=getState,proto3,oneof"`
}

type SemaphoreCommand_SetTimer struct {
	SetTimer *SemaphoreSetTimerRequest `protobuf:"bytes,3,opt,name=set_timer,json=setTimer,proto3,oneof"`
}

type SemaphoreCommand_SimulateFailure struct {
	SimulateFailure *SemaphoreSimulateFailureRequest `protobuf:"bytes,4,opt,name=simulate_failure,json=simulateFailure,proto3,oneof"`
}

func (*SemaphoreCommand_ChangeState) isSemaphoreCommand_Command() {}

func (*SemaphoreCommand_GetState) isSemaphoreCommand_Command() {}

func (*SemaphoreCommand_SetTimer) isSemaphoreCommand_Command() {}

func (*SemaphoreCommand_SimulateFailure) isSemaphoreCommand_Command() {}

type SemaphoreChangeStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         SemaphoreState         `protobuf:"varint,1,opt,name=state,proto3,enum=semaphore.SemaphoreState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemaphoreChangeStateRequest) Reset() {
	*x = SemaphoreChangeStateRequest{}
	mi := &file_semaphore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemaphoreChangeStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemaphoreChangeStateRequest) ProtoMessage() {}

func (x *SemaphoreChangeStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semaphore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemaphoreChangeStateRequest.ProtoReflect.Descriptor instead.
func (*SemaphoreChangeStateRequest) Descriptor() ([]byte, []int) {
	return file_semaphore_proto_rawDescGZIP(), []int{1}
}

func (x *SemaphoreChangeStateRequest) GetState() SemaphoreState {
	if x != nil {
		return x.State
	}
	return SemaphoreState_SEMAPHORE_STATE_RED
}

type SemaphoreGetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemaphoreGetStateRequest) Reset() {
	*x = SemaphoreGetStateRequest{}
	mi := &file_semaphore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemaphoreGetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemaphoreGetStateRequest) ProtoMessage() {}

func (x *SemaphoreGetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semaphore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemaphoreGetStateRequest.ProtoReflect.Descriptor instead.
func (*SemaphoreGetStateRequest) Descriptor() ([]byte, []int) {
	return file_semaphore_proto_rawDescGZIP(), []int{2}
}

type SemaphoreSetTimerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimerSeconds  int32                  `protobuf:"varint,1,opt,name=timer_seconds,json=timerSeconds,proto3" json:"timer_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemaphoreSetTimerRequest) Reset() {
	*x = SemaphoreSetTimerRequest{}
	mi := &file_semaphore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemaphoreSetTimerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemaphoreSetTimerRequest) ProtoMessage() {}

func (x *SemaphoreSetTimerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semaphore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemaphoreSetTimerRequest.ProtoReflect.Descriptor instead.
func (*SemaphoreSetTimerRequest) Descriptor() ([]byte, []int) {
	return file_semaphore_proto_rawDescGZIP(), []int{3}
}

func (x *SemaphoreSetTimerRequest) GetTimerSeconds() int32 {
	if x != nil {
		return x.TimerSeconds
	}
	return 0
}

type SemaphoreSimulateFailureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemaphoreSimulateFailureRequest) Reset() {
	*x = SemaphoreSimulateFailureRequest{}
	mi := &file_semaphore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemaphoreSimulateFailureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemaphoreSimulateFailureRequest) ProtoMessage() {}

func (x *SemaphoreSimulateFailureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_semaphore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemaphoreSimulateFailureRequest.ProtoReflect.Descriptor instead.
func (*SemaphoreSimulateFailureRequest) Descriptor() ([]byte, []int) {
	return file_semaphore_proto_rawDescGZIP(), []int{4}
}

type SemaphoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	State         SemaphoreState         `protobuf:"varint,3,opt,name=state,proto3,enum=semaphore.SemaphoreState" json:"state,omitempty"`
	TimerSeconds  int32                  `protobuf:"varint,4,opt,name=timer_seconds,json=timerSeconds,proto3" json:"timer_seconds,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemaphoreResponse) Reset() {
	*x = SemaphoreResponse{}
	mi := &file_semaphore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemaphoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemaphoreResponse) ProtoMessage() {}

func (x *SemaphoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_semaphore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemaphoreResponse.ProtoReflect.Descriptor instead.
func (*SemaphoreResponse) Descriptor() ([]byte, []int) {
	return file_semaphore_proto_rawDescGZIP(), []int{5}
}

func (x *SemaphoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SemaphoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SemaphoreResponse) GetState() SemaphoreState {
	if x != nil {
		return x.State
	}
	return SemaphoreState_SEMAPHORE_STATE_RED
}

func (x *SemaphoreResponse) GetTimerSeconds() int32 {
	if x != nil {
		return x.TimerSeconds
	}
	return 0
}

func (x *SemaphoreResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_semaphore_proto protoreflect.FileDescriptor

const file_semaphore_proto_rawDesc = "" +
	"\n" +
	"\x0fsemaphore.proto\x12\tsemaphore\"\xcb\x02\n" +
	"\x10SemaphoreCommand\x12K\n" +
	"\fchange_state\x18\x01 \x01(\v2&.semaphore.SemaphoreChangeStateRequestH\x00R\vchangeState\x12B\n" +
	"\tget_state\x18\x02 \x01(\v2#.semaphore.SemaphoreGetStateRequestH\x00R\bgetState\x12B\n" +
	"\tset_timer\x18\x03 \x01(\v2#.semaphore.SemaphoreSetTimerRequestH\x00R\bsetTimer\x12W\n" +
	"\x10simulate_failure\x18\x04 \x01(\v2*.semaphore.SemaphoreSimulateFailureRequestH\x00R\x0fsimulateFailureB\t\n" +
	"\acommand\"N\n" +
	"\x1bSemaphoreChangeStateRequest\x12/\n" +
	"\x05state\x18\x01 \x01(\x0e2\x19.semaphore.SemaphoreStateR\x05state\"\x1a\n" +
	"\x18SemaphoreGetStateRequest\"?\n" +
	"\x18SemaphoreSetTimerRequest\x12#\n" +
	"\rtimer_seconds\x18\x01 \x01(\x05R\ftimerSeconds\"!\n" +
	"\x1fSemaphoreSimulateFailureRequest\"\xb5\x01\n" +
	"\x11SemaphoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x05state\x18\x03 \x01(\x0e2\x19.semaphore.SemaphoreStateR\x05state\x12#\n" +
	"\rtimer_seconds\x18\x04 \x01(\x05R\ftimerSeconds\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status*`\n" +
	"\x0eSemaphoreState\x12\x17\n" +
	"\x13SEMAPHORE_STATE_RED\x10\x00\x12\x1a\n" +
	"\x16SEMAPHORE_STATE_YELLOW\x10\x01\x12\x19\n" +
	"\x15SEMAPHORE_STATE_GREEN\x10\x02B>Z<github.com/cbysousa/distributed-systems/internal/proto;protob\x06proto3"

var (
	file_semaphore_proto_rawDescOnce sync.Once
	file_semaphore_proto_rawDescData []byte
)

func file_semaphore_proto_rawDescGZIP() []byte {
	file_semaphore_proto_rawDescOnce.Do(func() {
		file_semaphore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_semaphore_proto_rawDesc), len(file_semaphore_proto_rawDesc)))
	})
	return file_semaphore_proto_rawDescData
}

var file_semaphore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_semaphore_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_semaphore_proto_goTypes = []any{
	(SemaphoreState)(0),                     // 0: semaphore.SemaphoreState
	(*SemaphoreCommand)(nil),                // 1: semaphore.SemaphoreCommand
	(*SemaphoreChangeStateRequest)(nil),     // 2: semaphore.SemaphoreChangeStateRequest
	(*SemaphoreGetStateRequest)(nil),        // 3: semaphore.SemaphoreGetStateRequest
	(*SemaphoreSetTimerRequest)(nil),        // 4: semaphore.SemaphoreSetTimerRequest
	(*SemaphoreSimulateFailureRequest)(nil), // 5: semaphore.SemaphoreSimulateFailureRequest
	(*SemaphoreResponse)(nil),               // 6: semaphore.SemaphoreResponse
}
var file_semaphore_proto_depIdxs = []int32{
	2, // 0: semaphore.SemaphoreCommand.change_state:type_name -> semaphore.SemaphoreChangeStateRequest
	3, // 1: semaphore.SemaphoreCommand.get_state:type_name -> semaphore.SemaphoreGetStateRequest
	4, // 2: semaphore.SemaphoreCommand.set_timer:type_name -> semaphore.SemaphoreSetTimerRequest
	5, // 3: semaphore.SemaphoreCommand.simulate_failure:type_name -> semaphore.SemaphoreSimulateFailureRequest
	0, // 4: semaphore.SemaphoreChangeStateRequest.state:type_name -> semaphore.SemaphoreState
	0, // 5: semaphore.SemaphoreResponse.state:type_name -> semaphore.SemaphoreState
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_semaphore_proto_init() }
func file_semaphore_proto_init() {
	if File_semaphore_proto != nil {
		return
	}
	file_semaphore_proto_msgTypes[0].OneofWrappers = []any{
		(*SemaphoreCommand_ChangeState)(nil),
		(*SemaphoreCommand_GetState)(nil),
		(*SemaphoreCommand_SetTimer)(nil),
		(*SemaphoreCommand_SimulateFailure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_semaphore_proto_rawDesc), len(file_semaphore_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_semaphore_proto_goTypes,
		DependencyIndexes: file_semaphore_proto_depIdxs,
		EnumInfos:         file_semaphore_proto_enumTypes,
		MessageInfos:      file_semaphore_proto_msgTypes,
	}.Build()
	File_semaphore_proto = out.File
	file_semaphore_proto_goTypes = nil
	file_semaphore_proto_depIdxs = nil
}
