# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: discovery.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'discovery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64iscovery.proto\x12\tdiscovery\"f\n\x10\x44iscoveryRequest\x12\x12\n\ngateway_id\x18\x01 \x01(\t\x12\x12\n\ngateway_ip\x18\x02 \x01(\t\x12\x15\n\rreadings_port\x18\x03 \x01(\x05\x12\x13\n\x0b\x63lient_port\x18\x04 \x01(\x05\"\x85\x01\n\x11\x44iscoveryResponse\x12\x13\n\x0bsource_name\x18\x01 \x01(\t\x12\x13\n\x0bsource_type\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x14\n\x0c\x63ontrol_port\x18\x04 \x01(\x05\x12\x14\n\x0c\x63ontrollable\x18\x05 \x01(\x08\x12\x0e\n\x06status\x18\x06 \x01(\tB>Z<github.com/cbysousa/distributed-systems/internal/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'discovery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/cbysousa/distributed-systems/internal/proto;proto'
  _globals['_DISCOVERYREQUEST']._serialized_start=30
  _globals['_DISCOVERYREQUEST']._serialized_end=132
  _globals['_DISCOVERYRESPONSE']._serialized_start=135
  _globals['_DISCOVERYRESPONSE']._serialized_end=268
# @@protoc_insertion_point(module_scope)
