# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: readings.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'readings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import temperature_pb2 as temperature__pb2
import air_quality_pb2 as air__quality__pb2
import lamppost_pb2 as lamppost__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ereadings.proto\x12\x08readings\x1a\x11temperature.proto\x1a\x11\x61ir_quality.proto\x1a\x0elamppost.proto\"\xe7\x01\n\rReadingPacket\x12\x13\n\x0bsource_name\x18\x01 \x01(\t\x12\x19\n\x11timestamp_unix_ms\x18\x02 \x01(\x03\x12\x36\n\x0btemperature\x18\x03 \x01(\x0b\x32\x1f.temperature.TemperatureReadingH\x00\x12\x34\n\x0b\x61ir_quality\x18\x04 \x01(\x0b\x32\x1d.airquality.AirQualityReadingH\x00\x12-\n\x08lamppost\x18\x05 \x01(\x0b\x32\x19.lamppost.LamppostReadingH\x00\x42\t\n\x07readingB>Z<github.com/cbysousa/distributed-systems/internal/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'readings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/cbysousa/distributed-systems/internal/proto;proto'
  _globals['_READINGPACKET']._serialized_start=83
  _globals['_READINGPACKET']._serialized_end=314
# @@protoc_insertion_point(module_scope)
