# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: air_quality.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'air_quality.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61ir_quality.proto\x12\nairquality\"a\n\x11\x41irQualityReading\x12\x0f\n\x07\x63o2_ppm\x18\x01 \x01(\x01\x12 \n\x18particulate_matter_ug_m3\x18\x02 \x01(\x01\x12\x19\n\x11\x61ir_quality_index\x18\x03 \x01(\x01\x42>Z<github.com/cbysousa/distributed-systems/internal/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'air_quality_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/cbysousa/distributed-systems/internal/proto;proto'
  _globals['_AIRQUALITYREADING']._serialized_start=33
  _globals['_AIRQUALITYREADING']._serialized_end=130
# @@protoc_insertion_point(module_scope)
