# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lamppost.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'lamppost.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elamppost.proto\"\x0f\n\rTurnOnMessage\"\x10\n\x0eTurnOffMessage\"\x11\n\x0fGetStateMessage\"!\n\x10GetStateResponse\x12\r\n\x05state\x18\x01 \x01(\x08\x42\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lamppost_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_TURNONMESSAGE']._serialized_start=18
  _globals['_TURNONMESSAGE']._serialized_end=33
  _globals['_TURNOFFMESSAGE']._serialized_start=35
  _globals['_TURNOFFMESSAGE']._serialized_end=51
  _globals['_GETSTATEMESSAGE']._serialized_start=53
  _globals['_GETSTATEMESSAGE']._serialized_end=70
  _globals['_GETSTATERESPONSE']._serialized_start=72
  _globals['_GETSTATERESPONSE']._serialized_end=105
# @@protoc_insertion_point(module_scope)
