# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: semaphore.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'semaphore.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsemaphore.proto\"\x14\n\x12\x43hangeStateMessage\"$\n\x13\x43hangeStateResponse\x12\r\n\x05timer\x18\x01 \x01(\x05\"\x11\n\x0fGetStateMessage\"A\n\x10GetStateResponse\x12\x1e\n\x05state\x18\x01 \x01(\x0e\x32\x0f.SemaphoreState\x12\r\n\x05timer\x18\x02 \x01(\x05*0\n\x0eSemaphoreState\x12\x07\n\x03Red\x10\x00\x12\n\n\x06Yellow\x10\x01\x12\t\n\x05Green\x10\x02\x42\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'semaphore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_SEMAPHORESTATE']._serialized_start=165
  _globals['_SEMAPHORESTATE']._serialized_end=213
  _globals['_CHANGESTATEMESSAGE']._serialized_start=19
  _globals['_CHANGESTATEMESSAGE']._serialized_end=39
  _globals['_CHANGESTATERESPONSE']._serialized_start=41
  _globals['_CHANGESTATERESPONSE']._serialized_end=77
  _globals['_GETSTATEMESSAGE']._serialized_start=79
  _globals['_GETSTATEMESSAGE']._serialized_end=96
  _globals['_GETSTATERESPONSE']._serialized_start=98
  _globals['_GETSTATERESPONSE']._serialized_end=163
# @@protoc_insertion_point(module_scope)
